config/routes.rb
Rails.application.routes.draw do

  default_url_options :host => "52.25.102.158"

  get 'notifications' => "notifications#configure"
  put 'notification' => "notifications#update"

  root :to => 'entries#index'

  resources :entries  do
    member do
      get 'analysis'

    end
    collection do
      get 'filter_by_concepts'
      get 'entries_from_concepts'
    end
  end

  get 'concepts' => "feeds#all_concepts"

  resources :feeds do
    member do
      get 'retrieve'
      post 'subscribe'
      post 'unsubscribe'
      get 'concepts'
    end

    collection do
      get 'filter_by_concepts'
      get 'filter_by_all_concepts'
    end
  end

  mount SuperfeedrEngine::Engine => SuperfeedrEngine::Engine.base_path # Use the same to set path in the engine initialization!
  match "/delayed_job" => DelayedJobWeb, :anchor => false, via: [:get, :post]

end

app/models/feed.rb
require 'digest/md5'

class Feed < ActiveRecord::Base

  has_many :entries, dependent: :destroy

  validates :url, uniqueness: true


  def secret
    Digest::MD5.hexdigest(created_at.to_s)
  end

  def notified params
    begin
      update_attributes(:status => params["status"]["http"])

      params['items'].each do |i|
        url_temp =  i["permalinkUrl"]
        #make permalink unique and discard permalinks with redirect
        next if Entry.all.pluck(:url).include? url_temp or  url_temp.include? "redirect"
        entries.create(:atom_id => i["id"], :title => HTMLEntities.new.decode(i["title"]), :url => i["permalinkUrl"], :image => extract_image(i), :content => i["content"])
      end
    rescue => e
      logger.error e.message
    end
  end

  def extract_image(resp)

    begin
      resp["standardLinks"].each do |l, v|
        h = v[0]
        next if h["type"].blank? or !h["type"].include? "image"
        return h["href"]
      end

    rescue => e
      logger.error e.message
      return nil
    end

    return nil
  end

end

app/controllers/feeds_controller.rb
class FeedsController < ApplicationController
  before_action :set_feed, only: [:show, :edit, :update, :destroy, :retrieve , :concepts]


  # GET /feeds
  def index
    @feeds = Feed.all
    #UserMailer.feedback_notification("testing").deliver
  end

  # GET /feeds/1
  def show
  end

  # GET /feeds/new
  def new
    @feed = Feed.new
  end

  # GET /feeds/1/edit
  def edit
  end

  def concepts
    @concepts = Concept.where(:entry_id => @feed.entries.pluck(:id))
  end

  def all_concepts
    @concepts = Concept.all
    render "feeds/all_concepts"
  end

  def filter_by_concepts

    @concepts = Concept.all
    concepts_ids = Concept.all.pluck(:id)

    if !params["relevance"].blank?
      @concepts =  Concept.where(:id => concepts_ids).where("relevance > ?" , params[:relevance])
      concepts_ids = @concepts.pluck(:id)
    end


    if !params["text"].blank?
      @concepts = Concept.where(:id => concepts_ids).where("lower(text) like ?" , "%#{params["text"].downcase}%")
    end

  end


  def filter_by_all_concepts

    @concepts = Concept.all
    concepts_ids = Concept.all.pluck(:id)

    #if !params["relevance"].blank?
    #  @concepts =  Concept.where(:id => concepts_ids).where("relevance > ?" , params[:relevance])
    #  concepts_ids = @concepts.pluck(:id)
    #end


    if !params["text"].blank?
      @concepts = Concept.where(:id => concepts_ids).where("lower(text) like ?" , "%#{params["text"].downcase}%")
    end

  end
  # GET /feeds/1/retrieve
  def retrieve
    body, ok = SuperfeedrEngine::Engine.retrieve(@feed)
    if !ok
      redirect_to @feed , notice: body
    else
      @feed.notified JSON.parse(body)
      redirect_to @feed , notice: "Retrieved and saved entries"
    end
  end

  # POST /feeds
  def create
    @feed = Feed.new(feed_params)

    if @feed.save
      body, ok = SuperfeedrEngine::Engine.subscribe(@feed, {:retrieve => true})
      if !ok
        redirect_to @feed, notice: "Feed was successfully created but we could not subscribe: #{body}"
      else
        if body
          @feed.notified JSON.parse(body)
        end
        redirect_to @feed, notice: 'Feed was successfully created and subscribed!'
      end
    else
      render :new
    end
  end

  # PATCH/PUT /feeds/1
  def update
    if @feed.update(feed_params)
      body, ok = SuperfeedrEngine::Engine.unsubscribe(@feed)
      if !ok
        render :edit, notice: "Feed was successfully updated, but we could not unsubscribe and resubscribe it. #{body}"
      else
        body, ok = SuperfeedrEngine::Engine.subscribe(@feed)
        if !ok
          render :edit, notice: "Feed was successfully updated, but we could not unsubscribe and resubscribe it. #{body}"
        else
          redirect_to @feed, notice: 'Feed was successfully updated.'
        end
      end
    else
      render :edit
    end
  end

  # DELETE /feeds/1
  def destroy
    body, ok =  SuperfeedrEngine::Engine.unsubscribe(@feed)
    if !ok
      redirect_to @feed, notice: body
    else
      @feed.destroy
      redirect_to feeds_url, notice: 'Feed was successfully destroyed.'
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_feed
      @feed = Feed.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def feed_params
      params.require(:feed).permit(:title, :url)
    end
end

app/helpers/feeds_helper.rb
module FeedsHelper
end

app/views/feeds/_all_concepts_table.html.erb
<table>
  <thead>
  <tr>
    <th>Concept</th>
  </tr>
  </thead>
  <tbody>
  <% concepts_array(@concepts.ids).each do |concept| %>
      <tr>
        <td><%= link_to concept , entries_from_concepts_entries_path(:concept => concept.split('(')[0]) %></td>
      </tr>
  <% end %>
  </tbody>
</table>

app/views/feeds/_concepts_table.html.erb
<table>
  <thead>
  <tr>
    <th>Concept</th>
    <th>Relevance</th>
  </tr>
  </thead>
  <tbody>
  <% @concepts.each do |concept| %>
      <tr>
        <!--<td><%#= concept.text %></td>-->
        <td><%= link_to concept.text , entries_from_concepts_entries_path(:concept => concept.text) %></td>
        <td><%= concept.relevance.to_f %></td>
      </tr>
  <% end %>
  </tbody>
</table>

app/views/feeds/_form.html.erb
<%= form_for(@feed) do |f| %>
  <% if @feed.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@feed.errors.count, "error") %> prohibited this feed from being saved:</h2>

      <ul>
      <% @feed.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :url %><br>
    <%= f.text_field :url %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/feeds/all_concepts.html.erb
<% provide(:title, 'Concepts') %>
<hr>
<h4 class="text-center">Filters</h4>

<!--<div class="row">-->
<!--<div class="small-10 medium-11 columns">-->
<!--<div class="range-slider" data-slider data-options="display_selector: #sliderOutput3; start: 0; end: 10;">-->
<!--<span class="range-slider-handle" role="slider" tabindex="0"></span>-->
<!--<span class="range-slider-active-segment"></span>-->
<!--</div>-->
<!--</div>-->
<!--<div class="small-2 medium-1 columns">-->
<!--<span id="sliderOutput3"></span>-->
<!--</div>-->
<!--</div>-->

<div class="row">
  <div class="columns large-4 text-center">

    <%= label "Text" , "text" %>
    <%= text_field_tag("text") %>

    <%#= label "relevance score" , "relevance score" %>
    <!--<span class="prefix"> greater than </span>-->
    <%#= text_field_tag("relevance") %>

    <div class="text-center">
      <%= button_tag "filter" , :onclick => "filter_concepts()" , :class => "tiny  radius success"%>
    </div>

  </div>
</div>

<hr>


<div id="feed_concepts">


  <%= render :partial => 'all_concepts_table' %>

</div>


<script type="text/javascript">
    function filter_concepts()
    {
        $.ajax({
            url: '<%= filter_by_all_concepts_feeds_path %>',
            type: 'GET',
            data: { text: $('#text').val()  }
        });
    }

</script>

app/views/feeds/concepts.html.erb
<% provide(:title, 'Concepts') %>
<hr>
<h4 class="text-center">Filters</h4>

<!--<div class="row">-->
<!--<div class="small-10 medium-11 columns">-->
<!--<div class="range-slider" data-slider data-options="display_selector: #sliderOutput3; start: 0; end: 10;">-->
<!--<span class="range-slider-handle" role="slider" tabindex="0"></span>-->
<!--<span class="range-slider-active-segment"></span>-->
<!--</div>-->
<!--</div>-->
<!--<div class="small-2 medium-1 columns">-->
<!--<span id="sliderOutput3"></span>-->
<!--</div>-->
<!--</div>-->

<div class="row">
  <div class="columns large-4 text-center">

    <%= label "Text" , "text" %>
    <%= text_field_tag("text") %>

    <%= label "relevance score" , "relevance score" %>
    <span class="prefix"> greater than </span><%= text_field_tag("relevance") %>

    <div class="text-center">
      <%= button_tag "filter" , :onclick => "filter_concepts()" , :class => "tiny  radius success"%>
    </div>

  </div>
</div>

<hr>


<div id="feed_concepts">


<%= render :partial => 'concepts_table' %>

</div>


<script type="text/javascript">
    function filter_concepts()
    {
        $.ajax({
            url: '<%= filter_by_concepts_feeds_path %>',
            type: 'GET',
            data: { text: $('#text').val() , relevance: $('#relevance').val() }
        });
    }

</script>

app/views/feeds/edit.html.erb
<h1>Editing Feed</h1>

<%= render 'form' %>

<%= link_to 'Show', @feed %> |
<%= link_to 'Back', feeds_path %>

app/views/feeds/filter_by_all_concepts.js.erb
$('#feed_concepts').html('')
$('#feed_concepts').html('<%= escape_javascript render "all_concepts_table" %>')

app/views/feeds/filter_by_concepts.js.erb
$('#feed_concepts').html('')
$('#feed_concepts').html('<%= escape_javascript render "concepts_table" %>')

app/views/feeds/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Feeds</h1>



<table>
  <thead>
    <tr>
      <th>Feed</th>
      <th>Entries count</th>
      <th>Concepts </th>
      <th colspan="4"></th>
    </tr>
  </thead>

  <tbody>
    <% @feeds.each do |feed| %>
      <tr>
        <td ><a href="<%= feed.url %>"><%= feed.title %></a></td>
        <td><%= link_to feed.entries.count , feed%></td>
        <td><%= link_to Concept.where(:entry_id => feed.entries.pluck(:id)).count , concepts_feed_path(feed) %></td>
        <td><%= link_to 'Retrieve', retrieve_feed_path(feed) %></td>
        <td><%= link_to 'Show', feed %></td>
        <td><%= link_to 'Edit', edit_feed_path(feed) %></td>
        <td><%= link_to 'Destroy', feed, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Feed', new_feed_path %>

app/views/feeds/new.html.erb
<h1>New Feed</h1>

<%= render 'form' %>

<%= link_to 'Back', feeds_path %>

app/views/feeds/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @feed.title %>
</p>

<p>
  <strong>Url:</strong>
  <%= @feed.url %>
</p>

<p>
  <strong>Status:</strong>
  <%= @feed.status %>
</p>

<%= link_to 'Retrieve', retrieve_feed_path(@feed) %> | <%= link_to 'Edit', edit_feed_path(@feed) %> | <%= link_to 'All Feeds', feeds_path %>

<%= render :partial => 'entries/index', :locals => {:entries =>  @feed.entries} %>