config/routes.rb
Rails.application.routes.draw do

  default_url_options :host => "52.25.102.158"

  get 'notifications' => "notifications#configure"
  put 'notification' => "notifications#update"

  root :to => 'entries#index'

  resources :entries  do
    member do
      get 'analysis'

    end
    collection do
      get 'filter_by_concepts'
      get 'entries_from_concepts'
    end
  end

  get 'concepts' => "feeds#all_concepts"

  resources :feeds do
    member do
      get 'retrieve'
      post 'subscribe'
      post 'unsubscribe'
      get 'concepts'
    end

    collection do
      get 'filter_by_concepts'
      get 'filter_by_all_concepts'
    end
  end

  mount SuperfeedrEngine::Engine => SuperfeedrEngine::Engine.base_path # Use the same to set path in the engine initialization!
  match "/delayed_job" => DelayedJobWeb, :anchor => false, via: [:get, :post]

end

app/models/entry.rb
class Entry < ActiveRecord::Base
  belongs_to :feed

  validates :atom_id, uniqueness: {scope: :feed_id}

  validates :url, uniqueness: true

  #validates :extracted_text, uniqueness: true

  has_many :concepts, dependent: :destroy

  has_many :keywords, dependent: :destroy

  default_scope {
    order('created_at DESC')
  }
  require 'unirest'
  after_create :alchemy_extract


  #if image column is blank, fetch image from flickr based on concept
  def image_fetch_from_flickr
    FlickRaw.api_key = '96c82ca534eeab3d74281a1aedae776b'
    FlickRaw.shared_secret = 'e90308d64bf86353'
    results = flickr.photos.search(:tags => self.concepts.first.text)

    if results and results.first
      info = flickr.photos.getInfo(:photo_id => results.first.id)
      url = FlickRaw.url_b(info)

      self.update(:image => url)
    end

  end


  def alchemy_extract

    begin
      #sentiment analysis
      sentiment_response = AlchemyAPI.search(:sentiment_analysis, url: self.url)
      #text extraction
      t_response = AlchemyAPI.search(:text_extraction, url: self.url)

      #self.update(:sentiment => sentiment_response["type"], :sentiment_score => sentiment_response["score"])

      self.update(:sentiment => sentiment_response["type"], :sentiment_score => sentiment_response["score"], :extracted_text => HTMLEntities.new.decode(t_response))

      #concept tagging
      concept_response = AlchemyAPI.search(:concept_tagging, url: self.url)

      concept_response.each do |c|
        concepts.create(:text => c["text"], :relevance => c["relevance"])
      end

        #keyword extraction
        #keyword_response = AlchemyAPI.search(:keyword_extraction, url: self.url)

        #keyword_response.each do |c|
        #  keywords.create(:text => c["text"], :relevance => c["relevance"])
        #end
    rescue => e
      puts "Error in alchemy====>" + e.message
    end

    if self.image.blank?
      image_fetch_from_flickr
    end
  end

end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController
  before_action :set_entry, only: [:show, :destroy, :analysis]

  # GET /entries
  # GET /entries.json
  def index
    @entries = Entry.all
  end

  def filter_by_concepts

    @entries = Entry.all
    entries_ids = Entry.all.pluck(:id)

    if !params["sentiment"].blank?
      @entries = Entry.where(:id => entries_ids).where("sentiment_score > ?", params[:sentiment])
      entries_ids = @entries.pluck(:id)
    end

    if !params["concept"].blank?
      @entries = Entry.where(:id => entries_ids).where(:id => Concept.where(:text => params["concept"]).pluck(:entry_id))
      entries_ids = @entries.pluck(:id)
    end

    if !params["text"].blank?
      @entries = Entry.where(:id => entries_ids).where("lower(extracted_text) like ?", "%#{params["text"].downcase}%")
    end


  end

  # GET /entries/1
  # GET /entries/1.json
  def show
  end

  def entries_from_concepts

    if !params["concept"].blank?
      @entries = Entry.where(:id => Concept.where(:text => params["concept"]).pluck(:entry_id))
    end

    @filter = params["concept"]

    render "entries/index"
  end

  # DELETE /entries/1
  # DELETE /entries/1.json
  def destroy
    @entry.destroy
    respond_to do |format|
      format.html { redirect_to entries_url, notice: 'Entry was successfully destroyed.' }
      format.json { head :no_content }
    end
  end


  def analysis

  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_entry
    @entry = Entry.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def entry_params
    params.require(:entry).permit(:feed_id, :atom_id, :title, :url, :content)
  end
end

app/helpers/entries_helper.rb
module EntriesHelper
end

app/views/entries/_index.html.erb
<% provide(:title, 'Entries') %>

<style>
.thumb {
    display: inline-block;
    width: 150px;
	height: 150px;
    margin: 0px;
    border: 4px solid #999999;
    background-position: center center;
    background-size: cover;
}
.thumb-flickr {
    display: inline-block;
    width: 150px;
	height: 150px;
    margin: 0px;
    border: 1px solid #999999;
    background-position: center center;
    background-size: cover;
}
</style>

<table>
  <thead>
    <tr>
      <th>Image</th>
      <th>Article</th>
      <!-- <th>Image</th> -->
      <!-- <th>Sentiment</th> -->
      <th>Sentiment score</th>
      <th>Permalink</th>
      <th colspan="1"></th>
    </tr>
  </thead>

  <tbody>
    <% entries.each do |entry| %>
      <tr>
        <td>
						
          <% if entry and entry.image and !entry.image.include? "flickr"%>
              <div class="thumb" style="background-image: url('<%= entry.image %>');"></div>
          <% elsif entry and entry.image %>
              <div class="thumb-flickr" style="background-image: url('<%= entry.image %>');"></div>
          <% end %>
	    </td>
		
        <td><h4><%= link_to entry.title, analysis_entry_path(entry) %></h4><br>
		<!--	<%= entry.created_at %></td>
                <td><%= entry.sentiment %></td> -->
        <td>
			<% if entry.sentiment_score and entry.sentiment_score >= 0 %>
			     <% $colorTemp = "#66CD00" %>
			   <% else %>
			     <% $colorTemp = "#FF0000" %>
			   <% end %>
			<span style="color:<%= $colorTemp %>;"><%= entry.sentiment_score %></span></td>
        <td><%= link_to "Permalink", entry.url %></td>
        <td><%= link_to 'Destroy', entry, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/entries/analysis.erb
<table>
  <thead>
  <tr>
    <th>Concept</th>
    <th>Relevance</th>
  </tr>
  </thead>
  <tbody>
  <% @entry.concepts.each do |concept| %>
      <tr>
        <td><%= concept.text %></td>
        <td><%= concept.relevance.to_f %></td>
      </tr>
  <% end %>
  </tbody>
</table>

<br>


<table>
  <thead>
  <tr>
    <th>Keyword</th>
    <th>Relevance</th>
  </tr>
  </thead>
  <tbody>
  <% @entry.keywords.each do |k| %>
      <tr>
        <td><%= k.text %></td>
        <td><%= k.relevance.to_f %></td>
      </tr>
  <% end %>
  </tbody>
</table>

app/views/entries/analysis.html.erb
<% provide(:title, @entry.title) %>

<style>
.thumb {
    display: inline-block;
    width: 320px;
	height: 320px;
    margin: 0px;
    border: 4px solid #999999;
    background-position: center center;
    background-size: cover;
}
.thumb-flickr {
    display: inline-block;
    width: 320px;
	height: 320px;
    margin: 0px;
    border: 1px solid #999999;
    background-position: center center;
    background-size: cover;
}
.container {
    width: 380px;
    padding: 20px;
}
</style>
<table>
	<tr>
		<td valign="top">

<!-- START CONTENT BLOCK -->
				
			<div class="container">
			  <h4>
			    <% if @entry and @entry.title %>
			       <%= @entry.title %>
			     <% end %>
			    </h4>
			  
			      <% if @entry and @entry.image and !@entry.image.include? "flickr"%>
			          <div class="thumb" style="background-image: url('<%= @entry.image %>');" align=left></div>
			      <% elsif @entry and @entry.image %>
			          <div class="thumb-flickr" style="background-image: url('<%= @entry.image %>');" align=left></div>
			      <% end %>
		
			      <%= simple_format @entry.extracted_text %>
			  
			</div>
			
<!-- END CONTENT BLOCK -->
						
		</td>
		<td valign="top" bgcolor="#e5e5e5">
			
<!-- START META BLOCK -->
		<p>
			    <% if @entry and @entry.url %>
			       <%= link_to "PermalinkURL", @entry.url %>
			     <% end %>
				<br>
				<% if @entry.sentiment_score and @entry.sentiment_score >= 0 %>
				     <% $colorTemp = "#66CD00" %>
				   <% else %>
				     <% $colorTemp = "#FF0000" %>
				   <% end %>
				Sentiment: <span style="color:<%= $colorTemp %>;"><%= @entry.sentiment_score %></span>
				<br>
			    <% if @entry and @entry.created_at %>
			       <%= @entry.created_at %>
			     <% end %>
		</p>
<!-- END META BLOCK -->
<!-- START CONCEPT BLOCK -->
			
			<table>
			  <thead>
			  <tr>
			    <th>Concept</th>
			    <th>Relevance</th>
			  </tr>
			  </thead>
			  <tbody>
			  <% @entry.concepts.each do |concept| %>
			      <tr>
					<td><%= link_to concept.text , entries_from_concepts_entries_path(:concept => concept.text) %></td>
			      	<td><%= concept.relevance.to_f %></td>
			      </tr>
			  <% end %>
			  </tbody>
			</table>
			
<!-- END CONCEPT BLOCK -->			
		</td>
	</tr>
</table>




<br>


<!--<table>-->
  <!--<thead>-->
  <!--<tr>-->
    <!--<th>Keyword</th>-->
    <!--<th>Relevance</th>-->
  <!--</tr>-->
  <!--</thead>-->
  <!--<tbody>-->
  <!--<%# @entry.keywords.each do |k| %>-->
      <!--<tr>-->
        <!--<td><%#= k.text %></td>-->
        <!--<td><%#= k.relevance.to_f %></td>-->
      <!--</tr>-->
  <!--<%# end %>-->
  <!--</tbody>-->
<!--</table>-->

app/views/entries/filter_by_concepts.js.erb
$('#entries').html('')
$('#entries').html('<%= escape_javascript render "index" , :entries => @entries %>')

app/views/entries/index.html.erb
<p id="notice"><%= notice %></p>


<!--
<h4 class="text-center">Filters</h4>

<div class="row">
  <div class="columns large-4 text-center">
      <%= label "concepts" ,"concepts" %>
      <%= select_tag 'concepts' , options_for_select( concepts_hash , @filter) , :include_blank => true %>

    <%= label "Text" , "text" %>
    <%= text_field_tag("text") %>

    <%= label "sentiment score" , "sentiment score" %>
    <span class="prefix"> greater than </span><%= text_field_tag("sentiment") %>

    <div class="text-center">
    <%= button_tag "filter" , :onclick => "filter_concepts()" , :class => "tiny  radius success"%>
    </div>

  </div>
</div>

<hr>
-->
<%= link_to 'List of Feeds', feeds_path %> | <%= link_to 'New Feed', new_feed_path %>

<div id="entries">
<%= render :partial => 'index', :locals => {:entries => @entries} %>
</div>

<br>


<script type="text/javascript">
  function filter_concepts()
  {
      $.ajax({
          url: '<%= filter_by_concepts_entries_path %>',
          type: 'GET',
          data: {concept : $('#concepts').val() , text: $('#text').val() , sentiment: $('#sentiment').val()}
      });
  }

</script>

app/views/entries/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Feed:</strong>
  <%= @entry.feed_id %>
</p>

<p>
  <strong>Atom:</strong>
  <%= @entry.atom_id %>
</p>

<p>
  <strong>Title:</strong>
  <%= @entry.title %>
</p>

<p>
  <strong>Url:</strong>
  <%= @entry.url %>
</p>

<p>
  <strong>Content:</strong>
  <%= @entry.content %>
</p>

<%= link_to 'Edit', edit_entry_path(@entry) %> |
<%= link_to 'Back', entries_path %>