config/routes.rb
Rails.application.routes.draw do

  default_url_options :host => "52.25.102.158"

  get 'notifications' => "notifications#configure"
  put 'notification' => "notifications#update"

  root :to => 'entries#index'

  resources :entries  do
    member do
      get 'analysis'

    end
    collection do
      get 'filter_by_concepts'
      get 'entries_from_concepts'
    end
  end

  get 'concepts' => "feeds#all_concepts"

  resources :feeds do
    member do
      get 'retrieve'
      post 'subscribe'
      post 'unsubscribe'
      get 'concepts'
    end

    collection do
      get 'filter_by_concepts'
      get 'filter_by_all_concepts'
    end
  end

  mount SuperfeedrEngine::Engine => SuperfeedrEngine::Engine.base_path # Use the same to set path in the engine initialization!
  match "/delayed_job" => DelayedJobWeb, :anchor => false, via: [:get, :post]

end

app/views/layouts/_topbar.html.erb
<nav class="top-bar" data-topbar role="navigation">
  <div class="top-bar-section">
    <ul class="left first-nav">

<%# add navigation links to this file %>
      <!--<li class="divider"></li>-->
      <li ><%= link_to 'Feeds', feeds_path %></li>
      <li ><%= link_to 'Entries', entries_path %></li>
      <li ><%= link_to 'Concepts', concepts_path %></li>
      <li ><%= link_to 'Notifications', notifications_path %></li>
    </ul>

  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "SuperFeedr with Alchemy" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= javascript_include_tag "application", 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>

  <body>
  <%= render "layouts/topbar" %>

    <%= yield %>

  </body>
</html>